services:
  db:
    container_name: cinematheque-db
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

  backend:
    container_name: cinematheque-backend
    image: ghcr.io/bolinocroustibat/cinematheque-backend:${TAG:-latest}
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - backend_data:/app/data
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - PORT=8000
      - CORS_ORIGIN=http://localhost:${APP_PORT:-3000}

  frontend:
    container_name: cinematheque-frontend
    image: ghcr.io/bolinocroustibat/cinematheque-frontend:${TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_TMDB_KEY=${VITE_TMDB_KEY}
        - VITE_OMDB_KEY=${VITE_OMDB_KEY}
        - VITE_API_URL=http://backend:8000
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - VITE_ENV=${VITE_ENV}
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_data:
