services:
  db:
    container_name: cinematheque-db
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

  backend:
    container_name: cinematheque-backend
    image: ghcr.io/bolinocroustibat/cinematheque-backend:${TAG:-latest}
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      # Application settings
      - ENVIRONMENT=${ENVIRONMENT:-unknown}
      - DEBUG=${DEBUG:-false}

      # Django settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}

      # Database settings
      - POSTGRES_DB=${POSTGRES_DB}

      # CORS settings
      - CORS_ORIGIN_ALLOW_ALL=${CORS_ORIGIN_ALLOW_ALL:-True}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:${FRONTEND_PORT:-4173}}
    depends_on:
      - db

  frontend:
    container_name: cinematheque-frontend
    image: ghcr.io/bolinocroustibat/cinematheque-frontend:${TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_TMDB_KEY=${VITE_TMDB_KEY}
        - VITE_OMDB_KEY=${VITE_OMDB_KEY}
        - VITE_SHEETS_API=${VITE_SHEETS_API}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - VITE_ENV=${VITE_ENV}
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
